### ISSUE TITLE
Chart colours should have greater contrast

### ISSUE THREAD

**Issue by shaneporter** [ONSdigital/sdg-indicators#181]
It is difficult to distinguish between the colours on the chart. One suggestion is to increase the contrast between the lines, another is to make the colours blue and grey with the "All" line in red

(from #152)

Estimate: 4 hours

**Comment by shaneporter** [comment]
Agreed that colours should have greater contrast, and making the 'all' line in red is a quick change. 

However, with only a few disaggregations, there will be large number of lines. I'm wondering whether variants of blue and grey will suffice.

What other colours can we use, after blue and grey?

**Comment by nathaneastwood** [comment]
Taken from style.ons.gov.uk

> Use various shades of a single colour, instead of multiple colours to help avoid colour blindness issues. This can be done by varying the luminance or saturation and holding the hue constant
>
> ![image](https://user-images.githubusercontent.com/9799530/28123591-3d66c12c-6719-11e7-8338-b0e377ff3735.png)

**Comment by MaxEngledew** [comment]
If we can't sort out the colour pallet for lots of lines a quick solution might be to add colour to enabled lines as you disable already colored enabled lines (see picture). Although maybe its more intuitive for users just to disable disaggregation variables to add colour to others.
![capture](https://user-images.githubusercontent.com/24583650/28317057-4d59b62c-6bbd-11e7-886d-b3a426dd5268.PNG)

**Comment by shaneporter** [comment]
@nathaneastwood - there are some shades in that palette that are virtually indistinguishable from one another. I'm not saying that this is easy, but the vast number of disaggregations _and_ resulting combinations means that there is no apparent solution to this as far as I can see.

**Comment by nathaneastwood** [comment]
I agree @shaneporter. I think the simplest thing to do is to define 8 colours and then have different shades of that colour for a single disaggregation though. At the moment we have different colours within a disaggregation which is quiet confusing. I'm not sure if you can generate hex values on the fly depending on different colours?

The palette idea is for interactions. So say you had selected Wales and Female, which were coloured Red and White, you would have Pink for the interaction?

**Comment by nathaneastwood** [comment]
Good points indeed. Maybe we could limit it in some way - only mix colours for two disaggregation interactions and any higher we use a different line type?

**Comment by shaneporter** [comment]
I took a look at the 'Ethnic Group' disaggregation for 5-2-1. There are *17* options. This is a lot for a single colour. 17 hues isn't going to work is it?

Lines styles and colours can help, but only up to a point. Therefore, I think a restriction on selections needs to be introduced. However, this doesn't fit with the 'nobody left behind' ethos. But, what's shown needs to be useful, too.

**Comment by nathaneastwood** [comment]
@AnnCorp do you have any thoughts?

**Comment by AnnCorp** [comment]
@shaneporter does anything you're doing re "Elements must have sufficient color contrast" in #308 sort any of this one or still need further discussion?

**Comment by shaneporter** [comment]
Unfortunately not @AnnCorp - those changes were for text elements only.

**Comment by dougmet** [comment]
Just looking at screenshots to what we have now I believe this is out of date. If not it will be surfaced in the next accessibility audit.
