### ISSUE TITLE
Chart zooming [estimate 2 days]

### ISSUE THREAD

**Issue by shaneporter** [ONSdigital/sdg-indicators#187]
Is it possible to have zoom functionality on the chart to more easily identify individual points?

(from #152)

Estimate: 2 days

**Comment by shaneporter** [comment]
So the good news is that chartjs has a plugin for this.

The bad news is that it doesn't seem to work with the latest version of chartjs, 2.6 at the time of writing. 2.6 is needed as part of the solution for #263.

The chartjs issue is described in https://github.com/chartjs/chartjs-plugin-zoom/issues/90.

As I write this, it's an issue that was raised just 2 days ago, so hopefully a fix will be forthcoming.

**Comment by shaneporter** [comment]
Things are looking positive for a fix on the chartjs zooming - I'll have to verify, but it seems that they've resolved the issue.

**Comment by AnnCorp** [comment]
Agreed with @dougmet and we think close this ticket and consider as part of Open SDG.
