### ISSUE TITLE
Headline data is not rounded

### ISSUE THREAD

**Issue by shaneporter** [ONSdigital/sdg-indicators#1870]
Data display in the headline table, sourced from `headlines_indicatorid.csv` is not rounded.

An example is indicator 1.a.2.

Related to #132.

**Comment by dougmet** [comment]
I can round in the Python code, although I'm always a little worried changing the data. From #64 we discussed using these ONS guidelines:

https://style.ons.gov.uk/data-visualisation/tables/number-rounding/

**Comment by AnnCorp** [comment]
Not sure if am understanding this issue correctly - may need to discuss.
We think it could be a good idea to round data displayed in the table to 2 decimal places where there are more than 2 decimal places (same with charts I guess or theyd be inconsistent). The raw data would remain unrounded.

**Comment by dougmet** [comment]
This was resolved

**Comment by dougmet** [comment]
Look at 1-a-2 now and it's rounded in the table but not in the source CSV as we'd like.
