### ISSUE TITLE
Headline data column widths

### ISSUE THREAD

**Issue by shaneporter** [ONSdigital/sdg-indicators#1874]
When it's just Year/Value, the equal distribution of column widths isn't too bad, but when there is a unit of measurement,. the Year column is given too much space.

Suggestion is to set this to a sensible fixed width, and give other columns a sensible width.

**Comment by dougmet** [comment]
When programmatically building tables should I add classes? `.year-col`, `.value-col` perhaps?

**Comment by dougmet** [comment]
From an accessibility point of view I'm also wondering if the year column should be a `<th scope="row">2015</th>` as here https://webaim.org/techniques/tables/data#th 

Probably this is another ticket though.

**Comment by dougmet** [comment]
Moved the scope=row issue to #1893

**Comment by AnnCorp** [comment]
@dougmet  does this link in with 1944??

**Comment by dougmet** [comment]
The way unit of measurement works now it's not on the headline chart (instead it acts as a filter). So this issue is out of date.
