### ISSUE TITLE
Bar chart not rendering values of 0

### ISSUE THREAD

**Issue by gingerbenw** [ONSdigital/sdg-indicators#1881]
Related to #353 - Apparently this used to be a feature of chartJS and has since been removed.

I will try and add [this fix](https://github.com/chartjs/Chart.js/issues/3915) to bring this feature back.

**Comment by AnnCorp** [comment]
Not for Sprint 10 - may just go on backlog

**Comment by JABedford** [comment]
@dougmet - possible closure
