### ISSUE TITLE
Year cells should have scope=row

### ISSUE THREAD

**Issue by dougmet** [ONSdigital/sdg-indicators#1893]
Split from #1874

For screen readers a table is much easier to navigate if columns and rows are labelled. We're lucky because all of our datasets are time series so the Year column can be used as a row label. To do this we change them to `<th>` tags.

```html
<th scope="row">2015</th>
```

as here https://webaim.org/techniques/tables/data#th

**Comment by AnnCorp** [comment]
@dougmet could you give an estimate on this please?

**Comment by dougmet** [comment]
I think this ticket should stay open. It may need some more thought with quarterly data (which would have two row headers or a `YearQ` column)

**Comment by dougmet** [comment]
Closing for open-sdg/open-sdg#106
