### ISSUE TITLE
Download multiple CSVs

### ISSUE THREAD

**Issue by ghost** [ONSdigital/sdg-indicators#2344]
How easy would it be to download multiple CSVs, not manually but in bulk, by specifying the Goal or Indicator code? Bonus points if we can also download CSVs for indicators relating to specific data sources.

Many thanks,
Chris

**Comment by dougmet** [comment]
Is this a user feature or something for us? In principle it's not too difficult -- except possibly the last one.

If we get to a point where the data source is different, and we can put a web service in front of it, then this will become very easy.

**Comment by norric1** [comment]
I'm glad to hear that downloading indicator and goal CSVs in bulk shouldn't be too difficult. This will be a user feature, ideally with a designated page containing dropdowns/checkboxes (but we are open to other ideas).

What are the first steps to adding this feature?

**Comment by norric1** [comment]
Bump

**Comment by dougmet** [comment]
Hi @AnnCorp I propose to close this as a wontfix. It's not that I don't think it's a good feature, it's more that I don't see an urgent user need. Perhaps we can integrate something like this into an enhanced search another time.

The data service could in principle create zips at the top and goal level.

**Comment by AnnCorp** [comment]
Think Poland have added something along these lines in their site.  Would need tighter requirement for this.  Could close or pass to Open SDG - review again after look at Poland site.

**Comment by AnnCorp** [comment]
Closing this ticket as Open SDG (and so now the UK site) has feature to bulk down load indicators.
