### ISSUE TITLE
Tabs not loading

### ISSUE THREAD

**Issue by norric1** [ONSdigital/sdg-indicators#2351]
https://github.com/datasciencecampus/sdg-indicators/issues/2335

**Comment by norric1** [comment]
Please can you help me to sort this, as I am unable to make any edits to the tool.

**Comment by norric1** [comment]
Brilliant - it's working again :) thanks.

**Comment by MaxEngledewAdmin** [comment]
I'm getting this issue too. The URL is changing but I'm not getting any display changes when selecting tabs.

**Comment by dougmet** [comment]
On the off chance this is 4-2-1, it takes quite a long time to load as it's really big. Assuming not, let me know if this persists, we're not seeing the issue and the console message from @MaxEngledewAdmin seemed to suggest it wasn't receiving `bootstrap.min.js` which one would think loads easily from the CDN.

**Comment by MaxEngledewAdmin** [comment]
Unfortunately I'm definitely getting it across all indicators

**Comment by AnnCorp** [comment]
Many people in our team are getting this issue though it never happens to me. My colleague Jo who gets the issue a lot is using Google Chrome Version 63.0.3239.132 (Official Build) (64-bit).

**Comment by AnnCorp** [comment]
The error msg Jo gets:
Failed to load resource: the server responded with a status of 500 (internal server error) bootstrap.min.is
Session.get onError checking if browser is safari cdn.loop11.com/my/loop11.is:1

**Comment by AnnCorp** [comment]
Before he went on leave Max was exploring this and thought it was something to do with the Loop11 code?

**Comment by shenavall** [comment]
Doug mentioned this and he seemed stumped.  I honestly can't see me progressing with it any more than Doug did.  However if Max has an idea about it it seems a good idea to me to wait until he gets back and explore that with him.

**Comment by AnnCorp** [comment]
@MaxEngledewAdmin When you're back please could you add any throughts on this? cheers

**Comment by Norric1Admin** [comment]
Had this issue again last week; had a search an no one else seems to have reported the same problem. Hopefully this link to where our tab styles are stored will shed some light https://github.com/ONSdigital/sdg-indicators/blob/401f94241b2495a57f5b037a436e30e03b28a4c8/_layouts/indicator.html

**Comment by MaxEngledewAdmin** [comment]
Ah, yes. Could be unrelated, but there is a loop11 reference in the console - since we're not using loop11 would it be worth disabling it and seeing if that helps?
![image](https://user-images.githubusercontent.com/32291046/41837914-cb075560-7856-11e8-8cfe-5c4e0e6dccfa.png)

**Comment by shenavall** [comment]
@MaxEngledewAdmin  could try that but ideally it would be good to be able to reproduce it first to see if whatever changes we make are having an effect.  Are you able to provide as much info as possible on...
- Which site (live or staging)
- Operating system
- Browser version
- Actions taken in the browser  (eg loaded site, clicked on goal xx, clicked on indicator xx, etc etc)

**Comment by MaxEngledewAdmin** [comment]
- Both sites
- Chrome 59 on Windows 7
- All indicators browsing through goal

Tabs are working on IE *shudder*

**Comment by shenavall** [comment]
I think Loop11 is a red herring.

Investigation revealed the following:

ONS Windows Laptop + Chrome 63: Doesn't Work
ONS Windows Laptop + IE : Works fine
Mac + Chrome 67 : Works fine
Ancient, non-work Windows laptop + Chrome 67 : Works fine

The most likely hypothesis is that there is a fix for whatever is going wrong in Chrome > 63

Normally not an issue for people as Chrome updates automatically.  But ONS have got the updates locked down. We could find out whoever is in charge of this and pester them to allow the update to 67?  In the meantime I would suggest using IE

**Comment by MaxEngledewAdmin** [comment]
Thanks @shenavall, agreed IE :-1: seems like the easiest solution for now! Odd that it works sometimes though...

**Comment by Norric1Admin** [comment]
Unfortunately I also get the error in IE.
![tabs_error](https://user-images.githubusercontent.com/37659239/41853225-363278fa-7885-11e8-8df7-5ee5dbe616b9.JPG)

**Comment by shenavall** [comment]
Strange @Norric1Admin it works fine for me in IE.  Could you check which version of IE you are on?
