### ISSUE TITLE
Dynamically increase page height based on filtering options

### ISSUE THREAD

**Issue by nathaneastwood** [ONSdigital/sdg-indicators#241]
When selecting lots of filtering options (take [this](https://datasciencecampus.github.io/sdg-indicators/9-2-1/) indicator as an example), the graph becomes very squashed. The graph height should dynamically adjust based on the number of filtering options selected.

**Comment by shaneporter** [comment]
Woah. The filters just don't work nicely with that number of options. Will most likely have to redesign them too.

**Comment by dougmet** [comment]
Child of #129
