### ISSUE TITLE
Zooming and panning

### ISSUE THREAD

**Issue by dougmet** [ONSdigital/sdg-indicators#2583]
How much effort to have a zoom +/- button and to allow panning around the map?

**Comment by shaneporter** [comment]
Shouldn't be too difficult to do.

**Comment by dougmet** [comment]
Hi @shaneporter, can you quickly describe any issues with this?

**Comment by shaneporter** [comment]
The existing zoom in/out code (when clicking on a region) was using a fixed origin point. The generic zoom in/out using the buttons was doing the zooming, but the origin was messed up, so you didn't end up where you expected to end up!

It may well not be that difficult to fix - but it certainly was a lot worse as I had it!

**Comment by dougmet** [comment]
Awesome, thanks. If one forgot about panning (only zooming) would that male it easier? Or better just to fix the lot in one go?

**Comment by AnnCorp** [comment]
Covered in Open SDG maps based on Leaflet - includes zooming etc
