### ISSUE TITLE
Multiple data changes can cause clashes

### ISSUE THREAD

**Issue by nathaneastwood** [ONSdigital/sdg-indicators#26]
There is currently no system in place for creating multiple changes and therefore submitting multiple PRs for the same file. This can cause confusion as people can't necessarily see that a change has already been made when on prose.io or the website itself.

**Comment by shaneporter** [comment]
Please clarify a bit. Are you saying that multiple users are not able to submit a pull request for the same file?

**Comment by nathaneastwood** [comment]
Sorry bud, I wrote this trying to have a conversation at the same time...never a good idea.

Essentially, person A can submit a PR, but those changes obviously won't be merged until the Data Manager accepts the changes. In the meantime, person B can also submit a change - but those changes could potentially clash with the changes submitted by person A (or they may be creating a duplicate PR). This is likely to happen with people who don't use the GitHub interface so is it possible to have some kind of indicator to say that data they are editing may not be the most up to date?

If you don't think this is sensible / feasible, then please close the issue :)

**Comment by shaneporter** [comment]
The approval of changes is the responsibility of the Data Manager, so it's up to them to resolve any conflicts between multiple PRs.

If the website states that the data isn't necessarily the most up-to-date, it will be confusing for people. They will ask 'well, why isn't it the latest? What _am_ I seeing?'

So if we simply leave off the 'this might not be the latest/your proposed changes may conflict with another user's etc...' disclaimer it will probably be the least confusing for the users, don't you think?

**Comment by nathaneastwood** [comment]
Yeah I agree with that. Good point.

I guess the data providers will have to have the awareness and check any PRs waiting to be dealt with? i.e. we will need to provide some form of training / manual?

**Comment by shaneporter** [comment]
GitHub should notify the Data Providers (they're the ones that approve PRs, I'm assuming) when a PR arises (or, we could have a hook that does that, specifically for a data related PR).

For the website users (so they don't repeatedly submit PRs for the _same_ changes), how about

> Proposed changes will be reviewed and may not appear immediately

Or something similar.

**Comment by nathaneastwood** [comment]
Sounds good to me :)

**Comment by dougmet** [comment]
Just to be clear. Is the outcome of this conversation that we should configure prose to display the notice: 

> Proposed changes will be reviewed and may not appear immediately

to be displayed after an update via prose?

**Comment by nathaneastwood** [comment]
No essentially someone can submit a change via prose.io which creates a PR. Until that PR is dealt with, someone else can come along and make a change to the data, submitting a second PR which may have merge clashes. So there are effectively two issues:

1. It is not clear when someone (yourself or another user) has already made a change.
2. It is not clear when your changes have actually been made (i.e. a user may be confused why their changes do not instantly appear)

**Comment by dougmet** [comment]
OK sure. This is probably OK for in-house users as they will know to check the PR list and can have a conversation with the data manager(s).  Does Prose give a link to the PR when you submit changes? I don't want to make a PR just to check but will if necessary.

**Comment by nathaneastwood** [comment]
No it doesn't. There is no warning that a PR has been made.

**Comment by dougmet** [comment]
I'll add this issue to my "stuff we could do if we fork prose" list. I'm
sure you could use the github API to check for relevant PRs.

On Mon, 10 Apr 2017 at 17:44, Nathan Eastwood <notifications@github.com>
wrote:

No it doesn't. There is no warning that a PR has been made.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/datasciencecampus/sdg-indicators/issues/26#issuecomment-293008102>,
or mute the thread

**Comment by dougmet** [comment]
No action for MVP
