### ISSUE TITLE
Download chart as image [estimate 1-2hrs]

### ISSUE THREAD

**Issue by shaneporter** [ONSdigital/sdg-indicators#264]
Users might not be aware that they can download the charts using the usual interaction to download an image (desktop users can right click, mobile users can touch and hold).

However, it _is_ possible that they might not be aware of this, and a 'Download chart' might help.

Is this something that anybody else thinks will be useful? It should be relatively quick to implement.

**Comment by AnnCorp** [comment]
@shaneporter how quick do you estimate 'relatively quick' to implement is in hours please?

**Comment by shaneporter** [comment]
1-2 hours

**Comment by AnnCorp** [comment]
Looked at some recent publications on ONS website and for charts you get a 'Download this chart' with green buttons underneath for 'Image' '.csv' and '.xls'. 
Maybe one to consider once have completed work on filtering/disaggregations if have enough resource left.

**Comment by shaneporter** [comment]
Sadly, this isn't as easy as it _was_; the changes I did for #2339 moved the legend out of the 'canvas' element and into html. This impacts on the 'chart as image' code and the resulting image does not include the legend.

**Comment by dougmet** [comment]
Thanks Shane. As discussed let's pause for feedback.

**Comment by dougmet** [comment]
Closed for open-sdg/open-sdg#73
