### ISSUE TITLE
Legend titles can be undescriptive

### ISSUE THREAD

**Issue by shaneporter** [ONSdigital/sdg-indicators#2729]
In some cases, depending on the data, the legend titles can be a little undescriptive.

![image](https://user-images.githubusercontent.com/2493614/38935897-661c6650-4317-11e8-90b1-45ec4f3c0a39.png)

In the top right of this screenshot, the _Yes_ and _No_ legend items aren't particularly descriptive. What happens if another 'sub-category' has the same items? How could those be distinguished? 

Perhaps we should differentiate the legend items with the sub-category? (Although #2339 is still quite fresh in the memory, although it has now been fixed.)

**Comment by dougmet** [comment]
Closing for now.
