### ISSUE TITLE
No error message, but metadata failed

### ISSUE THREAD

**Issue by ghost** [ONSdigital/sdg-indicators#2759]
Hello, please could you advise on why https://travis-ci.org/datasciencecampus/sdg-indicators/builds/370602289 has failed? I have removed forbidden characters + can't see anything obvious.

Thanks,
Chris

**Comment by dougmet** [comment]
It's saying:

> graph_title missing for published statistical indicator in _indicators/7-b-1.md

I think you need to set `data_non_statistical: true`

**Comment by dougmet** [comment]
Apologies. It is statistical. OK, in that case it needs a graph title

**Comment by Norric1Admin** [comment]
Thanks Doug.
