### ISSUE TITLE
Core code as libraries/packages separate from forked repos

### ISSUE THREAD

**Issue by brockfanning** [ONSdigital/sdg-indicators#2815]
One drawback of the fork-and-customise approach is that, after the customising is done, it's hard to pull in upstream improvements. A possible way around that is to package the "core" code into a separate repo which gets _used_ -- not forked -- similar to "libraries" like jQuery or Pandas. Just wanted to throw out some potential strategies in case this is something worth investigating.

For this repo (the Jekyll site) a straightforward method is to move all of the layouts, includes, and assets to a separate repo as a Jekyll "theme", and then use the [remote-theme plugin](https://github.com/benbalter/jekyll-remote-theme) here to reference it. It's nice because it doesn't require any refactoring -- just the addition of a .gemspec file. Another cool aspect is that the country sites can override things on a file-by-file basis, just by adding the overridden files to their repo -- the remote-theme plugin knows to use the local versions instead of the remote versions.

For [mangothecat/sdg-data](https://github.com/MangoTheCat/sdg-data) maybe it's possible to package/move the Python scripts into a separate repo (like "sdg-data-scripts"?) as a Python package, so that the forked repos can reference it in a requirements.txt file? I don't have much experience with Python packaging so I'm not sure about that one. I'm imagining in the future a script being added for SDMX, for example, and it being useful if the forked repos can easily get the upstream improvement.

Maybe goes without saying, but I should mention that these library/package repos would probably need semantic version numbers, so countries would know if a change was major (breaking), minor, or a bug fix. (The remote-theme plugin does allow "pinning" a particular tag to use, and I know requirements.txt files do allow some kind of version number syntax.)

**Comment by dougmet** [comment]
Hi @brockfanning, I think this is spot-on and we've been wrestling with the best way to separate content and code. I would say that inside the [mangothecat/sdg-data](https://github.com/mangothecat/sdg-data) most of the real code is already inside a python package that could be distributed separately.

In fact there are currently two. Both sitting in the `scripts` directory.

1. `sdg` which has all the code for processing raw data into the served data.
2. `yamlmd`, which is actually copied from [dougmet/yamlmd](https://github.com/dougmet/yamlmd) which is a small utility for reading Markdown files with Yaml headers and writing back out again.

I would like to improve `sdg` so that it uses object-orientation (it grew somewhat organically) and tests, but being in a package is a start.

**Comment by dougmet** [comment]
In fact we can move those packages immediately as we can just install them from git at build time. Good plan.

**Comment by brockfanning** [comment]
Sounds great!

**Comment by dougmet** [comment]
Hi @brockfanning and @philipashlock related to this we've now moved all our repos to ONSdigital who are taking ownership. The split ended up creating 3 repositories:

https://github.com/ONSdigital/sdg-indicators is the main site
https://github.com/ONSdigital/sdg-data holds the data
https://github.com/ONSdigital/sdg-build is a python package used to process the data

Thanks for the suggestion on the last one, that worked nicely.

So when cloning the website you don't need your own copy of `sdg-build` but you do the others. `sdg-data` is just pure data and will evolve the raw format. Users may choose to use a different backend so long as they provide the data service in the right way.

Our staging site is now at https://onsdigital.github.io/sdg-indicators/ but the prod is in the same place.

**Comment by dougmet** [comment]
We removed all python from `sdg-indicators` and but for one jekyll-module that we need to pull in the metadata it would almost be able to build on gh-pages again.

**Comment by brockfanning** [comment]
@dougmet Great news, thanks for the heads up!

I'm curious about your thoughts on the "Jekyll theme" idea for doing the same type of thing with the website. Here are some links to illustrate the basic idea, which I tried out with the US platform [here](https://github.com/brockfanning/sdg-indicators-jekyll). If you check out the [commits](https://github.com/brockfanning/sdg-indicators-jekyll/commits/master) you'll see it's just 2 steps, after copying the entire codebase to a new repo:

1. Add a couple of Gem-related files
2. Remove all folders except for these: _includes, _layouts, _sass, and assets

Then in the original repo ([here](https://github.com/brockfanning/sdg-indicators-content) is an example I did of the US platform) you can [remove these folders](https://github.com/brockfanning/sdg-indicators-content/commit/ee838660ddfd9e93beb3fc28453434b1c0757a47) and [update the config to use a remote theme](https://github.com/brockfanning/sdg-indicators-content/commit/c373f77eda525015fc516d47f5a40ce5670850fc).

Then in the future if you add features or fix bugs (like if you found a browser issue, for example) then you would fix it in the Jekyll theme repo. And any country that had forked `sdg-indicators` would easily be able to pull in the improvement by bumping their version of the remote theme. Countries would also be able to easily override any of the layouts/includes/assets, just by putting their own versions of the file in their forked `sdg-indicators` repo, where it would override the version in the remote theme.

**Comment by dougmet** [comment]
Absolutely, that looks perfect! So this would be the final break between country content and generic NRP. Also has the bonus that you can retro-fit it after you already cloned, provided your data has the right format. Yeah great plan.

**Comment by dougmet** [comment]
Fancy having a bash @shaneporter ? I think we just about have time. At least take a look and let me know what you think.

**Comment by shaneporter** [comment]
#2827

**Comment by AnnCorp** [comment]
Covered by jekyll theme already implemented. close ticket.
