### ISSUE TITLE
Fix deprecated wiki entries

### ISSUE THREAD

**Issue by dougmet** [ONSdigital/sdg-indicators#2823]
Doesn't need to be perfect. Mustn't be wrong. List of things to fix:

- [x] [About](https://github.com/ONSdigital/sdg-indicators/wiki/About) tiny fixes to ref multiple repos.
- [x] [Design Principles](https://github.com/ONSdigital/sdg-indicators/wiki/Design-Principles) Not wrong but want to fill it out.
- [x] [How Create NRP](https://github.com/ONSdigital/sdg-indicators/wiki/How-do-we-create-our-own-NRP) Need to reference the two repos.
- [x] [Clone your own](https://github.com/ONSdigital/sdg-indicators/wiki/Clone-your-own%21-Comprehensive-step-by-step-instructions-%28Windows%29) two repos
- [x] [Setup gh-pages](https://github.com/ONSdigital/sdg-indicators/wiki/How-to-set-up-GitHub-pages) this refers to how we used to build
- [x] [What need to change](https://github.com/ONSdigital/sdg-indicators/wiki/What-do-we-need-to-change) Make it clear what's in sdg-data and what's in sdg-indicators
- [x] [Deploying to gh pages](https://github.com/ONSdigital/sdg-indicators/wiki/Deploying-to-GitHub-Pages) Since the service this is possibly easier.
- [x] [Deploying with Travis](https://github.com/ONSdigital/sdg-indicators/wiki/Deploying-with-Travis) Pretty good but note that this is the same for sdg-data

**Comment by dougmet** [comment]
Still need to do the detailed walkthrough. Basically it's the same but you clone sdg-data and do the data reset, then you clone sdg-indicators and do all the manual resets.

**Comment by dougmet** [comment]
@MaxEngledewAdmin seeing as you did a great job with "clone your own" (I always miss some details). Maybe we can finish that one off together on Tuesday.

**Comment by MaxEngledew** [comment]
I'll finish this today

**Comment by AnnCorp** [comment]
Not sure if @MaxEngledewAdmin already finished this and if not, maybe one to look at when back from leave.

**Comment by MaxEngledewAdmin** [comment]
Apologies - still working on this.

**Comment by MaxEngledewAdmin** [comment]
Completed
