### ISSUE TITLE
Deploy to prod

### ISSUE THREAD

**Issue by dougmet** [ONSdigital/sdg-indicators#2825]
Wouldn't normally have an issue for this. But we haven't actually put the new data service into production yet. When we're happy that [staging](https://onsdigital.github.io/sdg-indicators/) is working OK let's release while there are plenty of people about to fix things.

cc- @MaxEngledew 
cc- @Norric1Admin 
cc- @AnnCorp 

Lots of testing please!

**Comment by MaxEngledewAdmin** [comment]
No issues changing [pages](https://github.com/ONSdigital/sdg-indicators/commit/780678a347e31a840ac37db06dca6d569841c316#diff-9f95d98b9055e254d42b902d2d097513)
