### ISSUE TITLE
Allow embedding of HTML-defined maps in Indicator page

### ISSUE THREAD

**Issue by shenavall** [ONSdigital/sdg-indicators#2830]
Indicators with GeoData in the csv file that have the metadata flag Show Map set are rendered in the Indicator page as a third "Map" tab beside the Graph and Table tabs. This uses ONS mapping based on the Geo Data.

As an alternative to this we want to be able to generate a map manually/interactively (eg with ESRI) which results in html that can be embedded into the indicator webpage. So we need the facility for the SDG team to define embedded map html for a particular indicator (eg as a new metadata property) and then when the page is rendered, for this to be detected and displayed in the map tab instead of the existing map solution

**Comment by AnnCorp** [comment]
Ticket no longer needed. - already covered.
