### ISSUE TITLE
Data not displaying 4.1.1

### ISSUE THREAD

**Issue by MaxEngledewAdmin** [ONSdigital/sdg-indicators#2833]
Not sure if its to do with the units column, but data for 4.1.1 is not displaying. E.g. Select key stage 1 and Percentage (%) with English proficiency (data exists in csv)

[Link](https://onsdigital.github.io/sdg-indicators/4-1-1/)

**Comment by Norric1Admin** [comment]
Had a look. I switched the Units from Subject Proficiency to Key Stage.
