### ISSUE TITLE
sdg-indicators build failing

### ISSUE THREAD

**Issue by MaxEngledewAdmin** [ONSdigital/sdg-indicators#2839]

**Comment by MaxEngledewAdmin** [comment]
https://travis-ci.org/ONSdigital/sdg-indicators/builds/404984189?utm_source=github_status&utm_medium=notification

**Comment by brockfanning** [comment]
@MaxEngledewAdmin I looked a bit into this - my impression from some brief experimenting was that there were some indicators that were lacking the 'indicator_sort_order' field, and the code here couldn't handle missing data for that field. A possible way to get the indicator sorting functionality back might be to make sure that all indicators have this field, and then add validation rules to ensure that it will never be missing. Is that something you might want to pursue, or are there other plans?

**Comment by dougmet** [comment]
Given the low frequency of changes to indicators this would be a fairly light one-off job. It's easy to add to validation. When cloning that would be copied through as well (if we check the reset scripts) so it shouldn't be a pain for anyone taking a new copy of the site.

**Comment by Norric1Admin** [comment]
The build is no longer failing, and we have not encountered this error since. Going to close the issue.
