### ISSUE TITLE
Prose broken

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#2861]
We are not able to upload data or metadata manually through Prose, since updating the [Gemfile](https://github.com/ONSdigital/sdg-indicators/commit/efbabf0e3618a1ff42bcb47b96c1c31518607412) in response to a recommended update to Jekyll (see below). The error occurs when authenticating Prose (green button, followed by 'authenticate account'), and reads...

 "**Error while loading data from Github. This might be a temporary issue. Please try again later.**"

1. This occurs for all users of the UK site, including those with read-only access. If a user with this error tries to edit the Rwanda or Ghana site it shows the same error. The Real Mike Bolton experimented with using incognito tabs and clearing the browser cache, but this only worked once.
2. Rwanda and Ghana users can both use Prose as normal for their NRPs (this can be verified by logging into an account without UK SDG admin permissions and making an update to Rwanda/Ghana through Prose - it works). Using that same account to try and edit UK gives not the above error, but an endless 'loading' screen.
3. When i rebuilt in Rwanda sdg-indicator repo I got a prompt for a Jekyll update - the same one that I approved just before Prose broke for UK NRP (See attached). I suspect that updating the [Gemfile](https://github.com/ONSdigital/sdg-indicators/commit/efbabf0e3618a1ff42bcb47b96c1c31518607412) caused a problem with Prose for that site, and now any users who authenticate via the UK NRP find Prose broken for all GitHub sites.

The recommended Jekyll update reads: "Known moderate severity security vulnerability detected in jekyll < 3.6.3 defined in Gemfile.lock. Gemfile.lock update suggested: jekyll ~> 3.6.3.  Always verify the validity and compatibility of suggestions with your codebase." This [article](https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/) on security vulnerabilities might help.

**Comment by brockfanning** [comment]
@Norric1Admin I'm having trouble recreating it. Some questions I'm wondering about:
1. Is it still happening?
2. For an affected user does it happen every time, or only some of the time? 
3. Could it be related to users that need to switch between multiple Github.com accounts?

**Comment by Norric1Admin** [comment]
@brockfanning 
1. Yes, it's still happening for anybody making changes to the ONS site. Are you able to make a pull request via the 'Edit' tab in our [Staging](https://onsdigital.github.io/sdg-indicators/17-10-1/#edit) site?
2. It happens every time, unless we're using a non-networked laptop. This suggests it could be a permissions error on our network.
3. Only accounts with 'read' access can make changes via the 'Edit' tab. This problem affects them too. The only workaround we have so far is to use a non-networked laptop or VM.

Thanks Brock.

**Comment by brockfanning** [comment]
@Norric1Admin I'm able to submit a PR through the edit tab, yes: https://github.com/ONSdigital/sdg-data/pull/283

The fact that it works for you on non-networked laptops, strongly implies that problem is in your network. One way to get more info might be to open Chrome on a networked laptop, open the developer tools (CTRL-SHIFT-j), click on the "Network" tab in the developer tools, and then proceed with trying to edit some data. When you get to the failure screen, take a look in the Network console and see what requests failed (and maybe take a screenshot).

**Comment by Norric1Admin** [comment]
Thanks Brock – it’s a 401 error: “Failed to load resource: the server responded with a status of 401 (Unauthorized)”. Does sound like a problem with our network permissions.

**Comment by Norric1Admin** [comment]
**Conclusion**: For whatever reason, Prose.io is blocked for users editing the NRP within our network (401 error / Admin blocked this location). Nobody has been able to find a solution to this, so I recommend finding an Jekyll-based alternative which will allow users to submit NRP edits.

Investigate [CloudCannon](https://cloudcannon.com/) - NEW ISSUE
