### ISSUE TITLE
Write out to SDMX format

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [ONSdigital/sdg-indicators#2891]
More information on SDMX project can be found [here](https://share.sp.ons.statistics.gov.uk/sites/SusIneq/SDG/Sample/NRP/SDMX/PoaP_SDMX.docx?Web=1)
(link to sharepoint)[can only be accessed by ONS staff]

**Comment by dougmet** [comment]
For each indicator, we need a DSD to map our labels for metadata fields, dissaggregations and column names to the official UN ones. Otherwise, this is just another output format.

It's XML based. There is a spec for a SOAP and REST version. There are docs here https://sdmx.org/?page_id=5008

**Comment by AnnCorp** [comment]
SDMX output being covered by work in Open SDG and sdg_build - see https://github.com/open-sdg/open-sdg/issues/194
