### ISSUE TITLE
Investigate replacement for Prose.io (Savvas)

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#2910]
Prose.io is not working on the site https://github.com/ONSdigital/sdg-indicators/issues/2861
Investigate a Jekyll-based alternative such as [CloudCannon](https://cloudcannon.com/)

**Comment by brockfanning** [comment]
In case it's helpful, here's a link to previous discussion of replacing Prose.io: https://github.com/GSA/sdg-indicators-usa/issues/891

**Comment by Norric1Admin** [comment]
It has to be ‘Octopub’, if only for the name! Thanks.

**Comment by brockfanning** [comment]
@philipashlock pointed out another to keep an eye on: [Delimiter](https://github.com/frictionlessdata/delimiter). It's still a work in progress but as more features are added it looks to be very promising.

**Comment by dougmet** [comment]
Also pinning a reminder that we considered forking Prose and working on it ourselves #38 but I will close this ticket down now.

**Comment by Norric1Admin** [comment]
Thanks @brockfanning and @dougmet for the suggestions! We'll get Savas to take a look in March.

**Comment by brockfanning** [comment]
Pointing to some investigation of Netlify CMS [here](https://github.com/open-sdg/open-sdg/issues/371).

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin do you think this is somethign that we should discuss at a Tech call?

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp yes - was briefly brought up in tech call on 29 July, and think we all agreed to spend longer talking about it at future call

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp I think this can be closed - we now have the config forms which essentially replace prose

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin agreed - I'll close.
