### ISSUE TITLE
Investigate feature branch that failed to deploy

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#2918]
- [Travis build](https://travis-ci.org/ONSdigital/sdg-indicators/builds/493176453?utm_source=github_status&utm_medium=notification)
- [Branch: CHUCK_TEST](https://github.com/ONSdigital/sdg-indicators/tree/CHUCK_TEST)
- [Remote deployment](http://35.230.144.178/chuck-test/)
I tried to override one of the Layout files on sdg-indicators/CHUCK_TEST but although the branch deployed these changes aren't showing. Please could you advise?

**Comment by dougmet** [comment]
Try http://sdg.**************.com/chuck-test/

**Comment by Norric1Admin** [comment]
Refreshed this [commit](https://github.com/ONSdigital/sdg-indicators/commit/6265fd237d2723b9637739a85e9f3a074f798bc9) on recommendation from @dougmet - checking whether 18.png has updated.
