### ISSUE TITLE
Display of quarterly data in charts (Savvas)

### ISSUE THREAD

**Issue by AnnCorp** [ONSdigital/sdg-indicators#2919]

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin is this one sorted?

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp not entirely sure what this ones about as could display quarterly data when this issue was made- https://sdgdata.gov.uk/8-6-1/

but might have been something to do with an improvement?

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp closing this one as it's already possible to report quarterly data in charts
