### ISSUE TITLE
Test across browsers and devices

### ISSUE THREAD

**Issue by AnnCorp** [ONSdigital/sdg-indicators#2930]
Need to ensure compliance with GDS service standard on designing for different browsers and devices: https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices

Need to user BrowserStack to work through the various requirements of the standard to discover any areas where we are not compliant.
Then need to set out what changes would need to be made to ensure compliance.

**Comment by SavvasStephanides** [comment]
Trying to access BrowserStack and keep getting this message:

<img width="529" alt="Screenshot 2019-03-20 at 08 14 41" src="https://user-images.githubusercontent.com/478770/54669084-60e50280-4ae8-11e9-89d2-fa181df875ed.png">

I'm pretty sure I signed up with the invitation I got in my emails. Not sure what I should do.

**Comment by AnnCorp** [comment]
Can Ian Kent or anyone else in your team help with this?

**Comment by SavvasStephanides** [comment]
Thanks @AnnCorp I'll sort something out regarding BrowserStack. In the meantime, I've done some quick tests on `ONSDigital/sdg-indicators` operability on mobile using Google Chrome's dev tools, to identify any "quick wins" (I haven't tested these on an actual device yet).


## 1. The ALPHA notice at the top creates a little "notch":
![image](https://user-images.githubusercontent.com/478770/54818191-9b899f00-4c90-11e9-8c47-b74985e824f1.png)


## 2. The chart titles seem to shrink to accommodate the screen size:

![image](https://user-images.githubusercontent.com/478770/54819333-7d716e00-4c93-11e9-9345-349e8d10b6c0.png)


## 3. The x-axis labels also seem to overlap with the source text below:

![image](https://user-images.githubusercontent.com/478770/54819369-99750f80-4c93-11e9-89df-8128a8f45f52.png)


## 4. These tabs seem to wrap when reaching the end of the screen:

![image](https://user-images.githubusercontent.com/478770/54819490-ec4ec700-4c93-11e9-80dd-809d2f357ac1.png)

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility tickets](https://trello.com/c/E40VA79G/549-accessibility-tickets)

**Comment by Norric1Admin** [comment]
This has been built into the process for DAC testing (see any Issue tagged `Accessibility`).
