### ISSUE TITLE
Options for showing Units type when only one unit type in data

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [ONSdigital/sdg-indicators#2953]
Currently the Units type option shows on the indicator page if there is a 'Units' column in the CSV. We have a row in the metadata sheet of the indicator file called 'Units option (Y/N)' which is automatically filled in depending on the CSV sheet. If we add the option to the metadata files (using metadata script), could we get the Units type option to show if 'Units option (Y/N)' = Y?

*UPDATE* 28/02/19
Discussed in SDG platform team and suggested another approach is to edit the code on the tool to do a similar thing - see thread for more information

**Comment by dougmet** [comment]
We could make Units dependent on fields in the metadata which would make it more flexible. This would affect all countries so it’s a fairly big change.

**Comment by LucyGwilliamAdmin** [comment]
We currently have a field in our local metadata files called "Units option (Y/N)" which was thought to be feeding through to the code but it actually isn't. So ideally, we'd want it to come from this.

**Comment by LucyGwilliamAdmin** [comment]
Currently if there's only one unit type in the Units column it looks like this on the NRP:
![image](https://user-images.githubusercontent.com/43404358/53578869-69dd5680-3b70-11e9-8aab-331dcb067026.png)

This makes it look like there's some user interaction available when there isn't.

Some possible solutions are:
- change how this would display if there is only one unit type (without the radio button)
- completely suppress this showing if there's only one unit type

**Comment by Norric1Admin** [comment]
`LucyGwilliamAdmin closed this 2 minutes ago`
`LucyGwilliamAdmin reopened this a minute ago`
Did you mean to do that? :smile:

**Comment by dougmet** [comment]
If there's only one unit type then you don't need a units column, you can just specify it in the metadata field: `computation_units`

**Comment by dougmet** [comment]
Or are you thinking ahead to SDMX where we'll always have a units column? If so then sure, a simple bit of logic in open-sdg can ignore this for one group.

**Comment by LucyGwilliamAdmin** [comment]
Yes, all indicator files now have a units column so I think that could work

**Comment by dougmet** [comment]
Looking ahead to some of the changes that SDMX will bring we will need to look at column descriptors. Then we could list column type from something like:

* Time Period (e.g. Year)
* Units (e.g. Percentage, Seasonality)
* Dissaggregation (e.g. Sex, Age)
* Attribute (observation level metadata)

By understanding all the different column types this could naturally be fixed. We can do a small fix in the meantime depending on the priority.

**Comment by Norric1Admin** [comment]
Close for now as we have a better solution (CSV-w)
