### ISSUE TITLE
Be able to choose columns to show as radio buttons instead of drop-down list

### ISSUE THREAD

**Issue by LucyGwilliamAdmin** [ONSdigital/sdg-indicators#2954]
Before we needed the 'Units' column on every single CSV (for SDMX), it was sometimes used for things that weren't necessarily a unit but needed a toggle rather than a drop down option. This is because with the dropdown option, another line is added to the graph but with the radio buttons, the line is replaced. 

One example is [8.5.2](https://sustainabledevelopment-uk.github.io/8-5-2/), where the Units is actually 'Percentage (%)' but we have been advised by the topic not to have the seasonally adjusted and not seasonally adjusted values on the same graph.

**Comment by LucyGwilliamAdmin** [comment]
Maybe we could do this using the metadata e.g. the key would be 'Toggle options' and the value would be a list of column names that you would want to show as radio buttons rather than a drop down option.

**Comment by dougmet** [comment]
Related to #2953 

Looks like we'll need to have column descriptions containing different types. Then any column listed as a "Units" type would get a radio button.

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin is this covered by the Series work, so this could be closed?

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp yes, covered by Series so closing
