### ISSUE TITLE
Password-protect Staging and test branches

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#2974]
How to password-protect the repos so that users must enter one before merging PRs?

**Comment by dougmet** [comment]
What's the problem you're solving here? Is it because you're not always sure which account you're on? 

We can strengthen the permissions, who has write access to master/develop etc. I don't think there's a way to force a password prompt. You could setup your browser to not store GitHub cookies and then you'd have to log in more regularly.

**Comment by Norric1Admin** [comment]
Hi @dougashton-ons - I've updated the title to better reflect what the team are after. The aim is to hide the Staging and test sites from sight, until the user enters the password. Possible solution to the problem you mentioned - can we have a password check at the PR/commit stage?

**Comment by dougmet** [comment]
ah OK. On the test server. I thought you meant here on GitHub. I'll have a play with the `.htaccess` files and see if I can keep the sites locked but leave the data open.

**Comment by Norric1Admin** [comment]
Thanks. I mean for the test server, but also the [Staging site](https://onsdigital.github.io/sdg-indicators/) which is GitHub-based.

**Comment by Norric1Admin** [comment]
Just encountered a popup box asking for the password on the test branch :smile:

**Comment by dougmet** [comment]
If we don't want the staging site to be public then it's best to stop using GitHub pages. The develop branch is already deployed to the test server (sdg-indicators) and so this should be identical to the GitHub pages version.

**Comment by Norric1Admin** [comment]
Happy to leave this feature just on the test branches for now - this is a good addition. Thanks :+1:
