### ISSUE TITLE
Update Cookies page

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#2983]
Our [Cookies page](https://github.com/ONSdigital/sdg-indicators/blob/develop/_pages/cookies.md) could be outdated. Need to review this and rewrite the page to reflect GDPR, so that it becomes representative of any new build (i.e. Cloned websites linking to Open SDG).

Related:
https://github.com/ONSdigital/sdg-indicators/issues/1865
https://github.com/ONSdigital/sdg-indicators/pull/1963
https://github.com/ONSdigital/sdg-indicators/pull/1941

**Comment by SavvasStephanides** [comment]
Apart from our usage of cookies for Google Analytics and recording contrast, I have noticed at least 2 other external services that store cookies in the browser:

* Cloudflare: [The Cloudflare site](https://support.cloudflare.com/hc/en-us/articles/200170156-What-does-the-Cloudflare-cfduid-cookie-do-) says that this is just to identify the user and does not store any identifiable information.
* Mapbox: I think this just stores the access token for Mapbox (used by Leaflet).

**Comment by LucyGwilliamAdmin** [comment]
@SavvasStephanides 

Do you know what Cloudflare is used for?

And do you know what type of cookie it uses so can be added to this list:
>Cookies for measuring use of services:

>- _ga
>- _gid
>- _gat

The access token for Mapbox belongs to use so would we still need to include that this is stored?

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin anything further to be done on this ticket?

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp don't think so - we updated the cookies page with some other cookies Savvas found we were using
