### ISSUE TITLE
Disable disaggregations under 'Map' or 'Embed' tabs

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#2985]
We would like to hide the disaggregation boxes (or grey them out) if the 'Map' or 'Embed' tabs are selected. See below an example embed and the code we used in the metadata.
https://sdg.mango-solutions.com/3-4-2-deploy/3-4-2/

```
embedded_map_html: >-
 <script type="text/javascript" src="https://pym.nprapps.org/pym.v1.min.js"></script>
 <script>document.querySelector("li.nav-item.embedded-map").addEventListener("click",function(){ var pymParent = new
 pym.Parent('embeddedmapview', 'https://www.ons.gov.uk/visualisations/dvc529/multiline/index.html', {});})</script>
```

**Comment by SavvasStephanides** [comment]
I think the position of the disaggregation boxes could be changed to better reflect the fact that this is part of the Chart or Table tabs but not of Map or Embed. Then hide/show accordingly. Maybe move them under the tabs and over the chart? Let me know what you think.

**Comment by Norric1Admin** [comment]
Hi @SavvasStephanides I think this would be a controversial idea, only because some of the indicators ([9.5.1](https://sustainabledevelopment-uk.github.io/5-2-2)) have very many disaggregations. Perhaps an option to hide the disaggregations sidebar if 'Map' or 'Embed' tabs are clicked? `div id="fields"`

**Comment by SavvasStephanides** [comment]
Thanks @Norric1Admin. If that's the case then just hiding the disaggregations for certain chart types would do.

**Comment by SavvasStephanides** [comment]
I've made an attempt at hiding the disaggregation toolbar ("subcategories") in my test environment. Let me know if you're happy and I'll make a pull request on the ONSDigital repo.

https://sustainabledevelopment-cyprus.github.io/4-2-1/

**Comment by Norric1Admin** [comment]
Nice! This really is an improvement. Is it also possible to hide the 'units' and expand the map horizontally, to fill the area where the categories were?

**Comment by SavvasStephanides** [comment]
@Norric1Admin Thanks! I'll get to it. Expanding the map might be a bit tricky but I'll figure something out

**Comment by SavvasStephanides** [comment]
Pull request: https://github.com/ONSdigital/sdg-indicators/pull/2993

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin any htoughts on this one?

**Comment by LucyGwilliamAdmin** [comment]
@AnnCorp yes - when map or embed tab is selected, the disaggregation side bar is hidden and the map/embed is expanded to full width e.g. [3.a.1](https://sdgdata.gov.uk/3-a-1/)
