### ISSUE TITLE
Make sure that the 'Unit multiplier' and 'Observation status' columns don't show as disaggregations on the NRP

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#2997]

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make sure that the 'Unit multiplier' and 'Observation status' columns don't show as disaggregations on the NRP](https://trello.com/c/qCzuXnmI/470-make-sure-that-the-unit-multiplier-and-observation-status-columns-dont-show-as-disaggregations-on-the-nrp)

**Comment by dougmet** [comment]
open-sdg/open-sdg#129

**Comment by dougmet** [comment]
This is all done in 0.5.0 so go ahead and start using these columns in the data
