### ISSUE TITLE
Set up Kyrgyzstan platform (Savvas)

### ISSUE THREAD

**Issue by AnnCorp** [ONSdigital/sdg-indicators#3007]
We have agreed to set up a SDG platform for Kyrgyzstan based on Open SDG.
Needs to be done by 12 April so Ann can discuss/demo to Kyrgyzstan contact during UNECE meeting 15/16 April. Also this fits with timing for work to be done while DAC running testing as implementing any changes recommended by DAC will be a high priority.
To be in English only initially and then we can add Russian later.
Platform team will aim to source one indicator for demo purposes, but we will liaise with UNSD further to discuss timelines and process for adding data/metadata (discussed previously using SDMX)

**Comment by AnnCorp** [comment]
Hi both @SavvasStephanides @Norric1Admin Quick queries:
1. why do we have https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-site-starter/ as the url for Kyrgyzstan ie why have the site-starter bit in the url
2. What's the location of the github code for the kyrgyzstan site please
many thanks!
Ann

**Comment by Norric1Admin** [comment]
Hi Ann, we can change these in the settings, but not at quickly as there are other files using this name. The repo names are...
sdg-data: https://github.com/sustainabledevelopment-kyrgyzstan/open-sdg-data-starter
sdg-indicators: https://github.com/sustainabledevelopment-kyrgyzstan/open-sdg-site-starter

Have removed 3-a-1 (using UK data) so now only [3-2-2](https://sustainabledevelopment-kyrgyzstan.github.io/open-sdg-site-starter/3-2-2/) is displaying.

**Comment by LucyGwilliamAdmin** [comment]
Almost done. One thing before this can be closed:
We discovered when in Kyrgyzstan that the Kyrgyzstan live site hasn't been set up. It needs to be set up at https://sustainabledevelopment-kyrgyzstan.github.io and the staging site needs to be set up at a diff URL.

**Comment by AnnCorp** [comment]
This was completed - closing ticket.
