### ISSUE TITLE
Data subcategories not appearing in IE {Bug]

### ISSUE THREAD

**Issue by AnnCorp** [ONSdigital/sdg-indicators#3029]
The categories aren’t available when you open the platform with Internet Explorer, meaning that most indicators have some or all data inaccessible (it’s still available from the CSV.)
This isn't a problem in Chrome
One example of this is 4.2.2.
![image](https://user-images.githubusercontent.com/24583831/55940925-0b100000-5c39-11e9-8e94-20a5dbe6d0a5.png)

**Comment by AnnCorp** [comment]
@SavvasStephanides @dougmet @Norric1Admin we need to look at this urgently please. Seems to have happened since the move to 0.5.0.
Ideas?

**Comment by SavvasStephanides** [comment]
It was my mistake. Made a pull request to fix this: https://github.com/ONSdigital/sdg-indicators/pull/3030

**Comment by AnnCorp** [comment]
@savvasstephanides many thanks for fixing so quickly.
From Chuck's email - adding here for reference:
"When Savvas made the change to hide disaggregations for map and embed fields, he used `for-each` instead of the older `for` command, which is supported by most browsers but apparently not IE. "
