### ISSUE TITLE
Code leak on OnsDigital site

### ISSUE THREAD

**Issue by SavvasStephanides** [ONSdigital/sdg-indicators#3045]
Some code is visible at the top of the site. Possibly Chris's polyfill code?

![image](https://user-images.githubusercontent.com/478770/56108823-b1b01580-5f45-11e9-9e24-f8747edc4359.png)

Seems like the code is created outside a `<script>` tag

![image](https://user-images.githubusercontent.com/478770/56108857-d86e4c00-5f45-11e9-93ad-38d3c20c0f2a.png)

**Comment by Norric1Admin** [comment]
I dealt with this on Friday - use 'empty cache and hard reload' and this will disappear.
