### ISSUE TITLE
'Alpha' and survey header improvement

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#3060]
The header is currently a banner overlying the page, which is separate from the site and follows you as you scroll down. This poses a problem on devices, especially with the added survey text.

Can we replace this with a site header segment, which pushes the page content down as it expands and stays at the top of the site instead of following the user? The format can stay the same.

**Comment by SavvasStephanides** [comment]
I guess this could be a discussion on where it is best to place the survey link design-wise. Does it _need_ to be on top of the page? Should we place the link on different locations on desktop and mobile?

**Comment by AnnCorp** [comment]
Clising - improvements to configurability made by Savvas.
