### ISSUE TITLE
FAQ page: convert to text

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#3080]
‘FAQ’ page does not indicate to the user that they accordions are expandable or collapsible. Additionally, the accordion menu elements under ‘Frequently asked question (FAQ)’ contain ARIA roles that are not appropriate: role="button”. Ensure that ARIA roles are appropriate for their given element. The following link illustrates how to mark-up accessible accordions: https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/accordion/accordion.html.

Remove the accordions so the sections are already expanded by default.

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility tickets](https://trello.com/c/E40VA79G/549-accessibility-tickets)

**Comment by Norric1Admin** [comment]
https://github.com/ONSdigital/sdg-indicators/commit/04870867a601c88b1686b286cd2a0e7de0277683

**Comment by SavvasStephanides** [comment]
Pull request: https://github.com/ONSdigital/sdg-indicators/pull/3104

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Sprint 12](https://trello.com/c/HZJO8O4J/576-accessibility-sprint-12)

**Comment by Norric1Admin** [comment]
##Description
This update removes the FAQ accordions in favour of text fields easily navigable by keyboard users.

##Screenshots
**Before**
![image](https://user-images.githubusercontent.com/37659239/57369896-adfb6180-7186-11e9-8d49-23df862d2db4.png)
**After**
![image](https://user-images.githubusercontent.com/37659239/57369918-bc497d80-7186-11e9-90a8-3462e5a64133.png)

##Successfully tested on...
- [ ] Windows: IE11
- [ ] Windows: Chrome
- [ ] Windows: Firefox
- [ ] Windows: Edge
- [ ] macOS: Chrome
- [ ] macOS: Firefox
- [ ] iOS: Safari 9.3
- [ ] iOS: Chrome
- [ ] Samsung: Chrome
- [ ] Samsuung: Samsung Internet

##User feedback and problems encountered...

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FAQ page: convert to text](https://trello.com/c/2hfQ5iFI/604-faq-page-convert-to-text)
