### ISSUE TITLE
Split up footer links

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#3085]
Links at the bottom of the page are in two columns, and are announced together. Consider dividing the links so they may be accessed individually when navigating in context. This can be achieved by using an unordered list (e.g. 'Contact us')

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility tickets](https://trello.com/c/E40VA79G/549-accessibility-tickets)

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Sprint 12](https://trello.com/c/HZJO8O4J/576-accessibility-sprint-12)

**Comment by SavvasStephanides** [comment]
## Description

Turn footer links into unordered list for easier screen reader access

## Screenshots

* No screenshots, due to screen-reader related fixes*


## Successfully tested on...
- [ ] Windows: IE11
- [ ] Windows: Chrome
- [ ] Windows: Firefox
- [ ] Windows: Edge
- [ ] macOS: Chrome
- [ ] macOS: Firefox
- [ ] iOS: Safari 9.3
- [ ] iOS: Chrome
- [ ] Samsung: Chrome
- [ ] Samsung: Samsung Internet

## User feedback and problems encountered...

**Comment by SavvasStephanides** [comment]
Pull requests: https://github.com/ONSdigital/sdg-indicators/pull/3120 and https://github.com/open-sdg/open-sdg/pull/167

**Comment by LucyGwilliamAdmin** [comment]
@SavvasStephanides I don't know how we can test this as it's made on open-sdg branch?

**Comment by SavvasStephanides** [comment]
@LucyGwilliamAdmin forgot to include a link to my test branch. See updated template comment above under Description 👆

**Comment by LucyGwilliamAdmin** [comment]
![image](https://user-images.githubusercontent.com/43404358/57786202-fbe60b80-772a-11e9-8a6d-7d43c6b415d1.png)

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Split up footer links](https://trello.com/c/IJLAXW6B/609-split-up-footer-links)

**Comment by LucyGwilliamAdmin** [comment]
@Norric1Admin I think the branch link might actually be https://sdg.mango-solutions.com/a11y-footer-scss/ rather than https://sdg.mango-solutions.com/a11y-footer (what's in description)

**Comment by Norric1Admin** [comment]
The footer-scss link doesn't show the footer split up. I've made a copy of the original branch as a11y-footer has disappeared from the Mnago server. Link: https://sdg.mango-solutions.com/a11y-footer2

**Comment by LucyGwilliamAdmin** [comment]
This is now in Open SDG V0.8.0 so closing this issue
