### ISSUE TITLE
Alter contrast links to clarify what is meant

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#3087]
The contrast buttons need to state more clearly what they do.

Links are present that are not descriptive of the destination or purpose in or out of context. “I located duplicate ‘a’ links which are confusing as I do not know what their purpose is.” Ensure that links contain text that is unique and descriptive to enable users to accurately determine their destination or purpose (`aria-label=”___”`).

Let's try having the words 'Enable high contrast' in the title bar. When clicked it changes to say 'Normal...'. Alternatively, we could have  'high contrast' checkbox (remember to include aria tag for screen readers.

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility tickets](https://trello.com/c/E40VA79G/549-accessibility-tickets)

**Comment by LucyGwilliamAdmin** [comment]
## Description

## Screenshots
**Before**

**After**


## Successfully tested on...
- [ ] Windows: IE11
- [ ] Windows: Chrome
- [ ] Windows: Firefox
- [ ] Windows: Edge
- [ ] macOS: Chrome
- [ ] macOS: Firefox
- [ ] iOS: Safari 9.3
- [ ] iOS: Chrome
- [ ] Samsung: Chrome
- [ ] Samsung: Samsung Internet

## User feedback and problems encountered...

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility: Sprint 14](https://trello.com/c/80w0TtAV/586-accessibility-sprint-14)

**Comment by Norric1Admin** [comment]
@SavvasStephanides created a mock-up of this, which is clear and effective. https://codepen.io/anon/pen/BeWvbd

**Comment by LucyGwilliamAdmin** [comment]
I like the button, definitely a lot clearer - could it be in a different colour to math the rest of the website?

**Comment by Norric1Admin** [comment]
Good point, although I do like how it is now as it [passes contrast checks](https://webaim.org/resources/contrastchecker/). Open to ideas.

**Comment by SavvasStephanides** [comment]
Pull request here: https://github.com/ONSdigital/sdg-indicators/pull/3134

Happy to hear your thoughts on colouring or functionality

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Alter contrast links to clarify what is meant](https://trello.com/c/VauK4II0/611-alter-contrast-links-to-clarify-what-is-meant)

**Comment by Norric1Admin** [comment]
https://github.com/ONSdigital/sdg-indicators/pull/3184
@SavvasStephanides This didn't work as hoped. Think that moving the contrast toggle to below the main goals logo could be the easiest way around this problem. Please help me to conduct further resizing/moving tests on [ContrastToggle3](https://github.com/ONSdigital/sdg-indicators/tree/ContrastToggle3).
![image](https://user-images.githubusercontent.com/37659239/60129510-0a452f80-978d-11e9-928d-ece9b19f5968.png)

**Comment by LucyGwilliamAdmin** [comment]
This is now in Open SDG v0.8.0 so closing this issue
