### ISSUE TITLE
Rewrite 'Alpha' header (survey link)

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#3093]
The ‘click here’ link present in the ‘Alpha’ phase disclaimer is not descriptive of its destination or purpose when navigating out of context. Ensure that link text is unique and descriptive to help users identify the links destination or purpose when navigating out of context. This could be visually hidden from users with CSS.

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility tickets](https://trello.com/c/E40VA79G/549-accessibility-tickets)

**Comment by LucyGwilliamAdmin** [comment]
## Description

## Screenshots
**Before**

**After**


## Successfully tested on...
- [] Windows: IE11
- [] Windows: Chrome
- [ ] Windows: Firefox
- [ ] Windows: Edge
- [ ] macOS: Chrome
- [ ] macOS: Firefox
- [ ] iOS: Safari 9.3
- [ ] iOS: Chrome
- [ ] Samsung: Chrome
- [ ] Samsung: Samsung Internet

## User feedback and problems encountered...

**Comment by Norric1Admin** [comment]
First attempt: https://github.com/ONSdigital/sdg-indicators/pull/3021/files
Brock may have a more customisable solution with https://github.com/open-sdg/open-sdg/pull/147

**Comment by AnnCorp** [comment]
Closing as content in banner already changed following review by UR lead.
