### ISSUE TITLE
Warn users of external links

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#3094]
Many of the links on the ‘About’ page direct users to external websites without informing them. Ensure that links to external destinations can be easily identified by including this in the link text. This can be visually hidden using CSS (`<span class="visuallyhidden">`).

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility tickets](https://trello.com/c/E40VA79G/549-accessibility-tickets)

**Comment by LucyGwilliamAdmin** [comment]
## Description

## Screenshots
**Before**

**After**


## Successfully tested on...
- [] Windows: IE11
- [] Windows: Chrome
- [ ] Windows: Firefox
- [ ] Windows: Edge
- [ ] macOS: Chrome
- [ ] macOS: Firefox
- [ ] iOS: Safari 9.3
- [ ] iOS: Chrome
- [ ] Samsung: Chrome
- [ ] Samsung: Samsung Internet

## User feedback and problems encountered...

**Comment by AnnCorp** [comment]
Closing as this is AAA and we are working to AA standard.
