### ISSUE TITLE
SDG acronym defined

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#3095]
The acronyms ‘SDG’ is not expanded in its first instance. This means that users who are unfamiliar with the acronym may not understand its purpose or meaning.

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility tickets](https://trello.com/c/E40VA79G/549-accessibility-tickets)

**Comment by LucyGwilliamAdmin** [comment]
## Description

## Screenshots
**Before**

**After**


## Successfully tested on...
- [] Windows: IE11
- [] Windows: Chrome
- [ ] Windows: Firefox
- [ ] Windows: Edge
- [ ] macOS: Chrome
- [ ] macOS: Firefox
- [ ] iOS: Safari 9.3
- [ ] iOS: Chrome
- [ ] Samsung: Chrome
- [ ] Samsung: Samsung Internet

## User feedback and problems encountered...

**Comment by LucyGwilliamAdmin** [comment]
@Norric1Admin which page?

**Comment by AnnCorp** [comment]
Expert review assessed some content changes. Resource focussed on achieving AA, so won't be actioning AAA fixes currently.
