### ISSUE TITLE
Reorder <H#> header tags on the indicator page

### ISSUE THREAD

**Issue by Norric1Admin** [ONSdigital/sdg-indicators#3096]
The heading structure of the ‘Good health and well-being’ page is not logical because the ‘Sub-categories’ heading increases by more than one level. This means that screen reader users may not be able to accurately determine the structure of content on the page. “While navigating through the headings list out of context, I located headings that jump from H2 to H4. These do not follow a logical hierarchical heading structure and would benefit from following a consecutive order to enable users to better understand page layout.”

**Comment by Norric1Admin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Accessibility tickets](https://trello.com/c/E40VA79G/549-accessibility-tickets)

**Comment by LucyGwilliamAdmin** [comment]
## Description

## Screenshots
**Before**

**After**


## Successfully tested on...
- [] Windows: IE11
- [] Windows: Chrome
- [ ] Windows: Firefox
- [ ] Windows: Edge
- [ ] macOS: Chrome
- [ ] macOS: Firefox
- [ ] iOS: Safari 9.3
- [ ] iOS: Chrome
- [ ] Samsung: Chrome
- [ ] Samsung: Samsung Internet

## User feedback and problems encountered...

**Comment by AnnCorp** [comment]
Resource focussed on achieving AA, so won't be actioning AAA fixes currently.
