### ISSUE TITLE
Use a custom.scss file to avoid overriding default.scss

### ISSUE THREAD

**Issue by brockfanning** [ONSdigital/sdg-indicators#3130]
To make future Open SDG upgrades easier, any custom CSS should go into a "custom.scss" file, which gets loaded after the Open SDG version of "default.scss".

The steps to do this are to try and extract all the customisations made, so far, to default.scss, and move them into a new custom.scss file. And then use the [custom_css](https://github.com/open-sdg/open-sdg-site-starter/blob/develop/_config.yml#L125) config setting to load the custom.scss file. After this is done, the default.scss file can be deleted.

**Comment by dougmet** [comment]
agreed. At some point we had this, I'm sure.

**Comment by brockfanning** [comment]
I'm closing this, because unless I'm mistaken there is no longer any custom CSS in this implementation.
