### ISSUE TITLE
Goal URL redirects

### ISSUE THREAD

**Issue by brockfanning** [ONSdigital/sdg-indicators#3285]
Hi all, I recently submitted [this commit](https://github.com/ONSdigital/sdg-indicators/commit/d05df4eab46711be3fc97dc0941825883368344a) and it was merged. I'm only now remembering that you had redirects implemented for those goal pages (see the `redirect_from` in each goal page that was deleted). So, as of that commit, those redirects are no longer working.

If you are OK with dropping those redirects, there is nothing that you need to do. But if you still want to have those goal redirects, I believe you'll want to revert that commit. Let me know if there's any way I can help, and sorry for the oversight.

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin @SavvasStephanides can this ticket be closed?

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin one to close?

**Comment by LucyGwilliamAdmin** [comment]
Agree
