### ISSUE TITLE
Increased metadata checks for complete indicators

### ISSUE THREAD

**Issue by dougmet** [ONSdigital/sdg-indicators#329]
When someone is raising the `reporting_status` to `complete` we want to increase the checks in `scripts/build/metadatacheck.py`:

- [ ] Check for all required fields in one go

What are the required fields for a completed indicator? Off the top of my head they include:

1. `computation_units`
1. `graph_title` (statistical only)
1. `source_organisation_1`
1. `national_indicator_description`

- [ ] Check correct values

For fields that have select elements in the `_config.yml` we should check that the value is an allowed value. This isn't a problem for prose users but anyone directly committing data from git will need this checking.

**Comment by AnnCorp** [comment]
Agreed not priority for Sprint 8

**Comment by dougmet** [comment]
Needs to move to open-sdg/sdg-build.
