### ISSUE TITLE
Make content changes across UK site

### ISSUE THREAD

**Issue by phillipgardiner** [ONSdigital/sdg-indicators#3392]
@phillipgardiner to address a number of content changes required across the site including:

Known changes are:
About page - Increase white space between each bullet point (this might be controlled by Css?)
Guidance page - introduce bullet points to reduce sentence length and help scanning
Publications page - Delete page title 'Putting the numbers into context'
Publications page - Make 'Publications' page title
Publications page - Ensure all descriptions start on a separate line
Updates page - Make 'updates on sustainable development goals' page title

Any other simple mark up changes across the SDG pages identified.

The scope of changes will be limted to the   non-data pages: About, Guidance, Publication etc. Work on any data pages would need to be done in discussion with Data team (text may need to be discussed with topic experts).

A feature branch called 'content-changes' has been created by @SavvasStephanides on which the changes can be made.

**Comment by phillipgardiner** [comment]
Content changes have been made to the following pages:
- about.md
- accessibility statement.md
- cookies.md
- faq.md
- publications.md
- userpersonas.md

**Comment by phillipgardiner** [comment]
@AnnCorp @SavvasStephanides Through undertaking the updating of content via marking a couple of issues are still outstanding which cannot be resolved via markdown and likely to require development effort, these are: 

1) Removal of 'guidance' page from top navigation. It is thought this page is no longer required due to all information being captured on the About page (this may be an Open SDG change?)
 
2) Different design to the 'Updates pages' (as shown in the content word document)
 
3) 'Back to top' links are required to be located on right hand side of the page and styled according to GDS standards

4) Bullet points to be indented more within the pages (css)

5) Additional spacing to be added to bullet points (css)

**Comment by SavvasStephanides** [comment]
Thanks @phillipgardiner 

> Removal of 'guidance' page from top navigation. It is thought this page is no longer required due to all information being captured on the About page (this may be an Open SDG change?)

Navigation items can be configured from the UK site level, [from here](https://github.com/ONSdigital/sdg-indicators/blob/develop/_config.yml#L89)

> Different design to the 'Updates pages' (as shown in the content word document)

Yes, I believe these changes might need development on the Open SDG level.

> 'Back to top' links are required to be located on right hand side of the page and styled according to GDS standards

Yes, this will probably need some development, but I'm thinking maybe these can be marked in the Markdown files with a class (`<a href="#top" class="backToTopLink">Back to top</a>`) and styled with CSS at a later date. What are your thoughts Phill and @brockfanning?

> 4 and 5

Definitely a CSS change is needed here, as discussed yesterday.

**Comment by AnnCorp** [comment]
@phillipgardiner could we review what's remaining on this please and if could be broken into other tickets.

**Comment by phillipgardiner** [comment]
@AnnCorp Yep happy to close this ticket, the parts not done have already been split out into additional tickets #3397, #3393, #3395.
