### ISSUE TITLE
Improve 'back to top' links

### ISSUE THREAD

**Issue by phillipgardiner** [ONSdigital/sdg-indicators#3393]
The service currently has back to top links on two pages FAQ and Publications. These have been style using markdown only. 

Work is required to bring these links inline with GDS standards and design. The standard to follow can be found here: https://government-frontend.herokuapp.com/component-guide/back-to-top

![image](https://user-images.githubusercontent.com/60919820/85390062-2fa37f80-b540-11ea-9bd2-f640020c9aad.png)

An active example of this can be found here: https://www.gov.uk/government/publications/financial-sanctions-consolidated-list-of-targets/consolidated-list-of-targets#contents

**Comment by AnnCorp** [comment]
@phillipgardiner could this be closed now?

**Comment by AnnCorp** [comment]
@phillipgardiner can this current ticket 3393 be closed too please?

**Comment by phillipgardiner** [comment]
@AnnCorp , as far as i am aware this has not been addressed yet. Thinking about it in hindsight it may be that this arrow for the link could have been added in markup?

**Comment by phillipgardiner** [comment]
@brockfanning think this may be relevant on the mobile tab page to?

**Comment by phillipgardiner** [comment]
Back to top links would appear in bottom left of pages

**Comment by AnnCorp** [comment]
@phillipgardiner please could we add in the relevant GDS stuff in this issue. Thanks.

**Comment by phillipgardiner** [comment]
@AnnCorp Could this be added to OpenSDG? as even on OpenSDG a consistent style is required.

**Comment by AnnCorp** [comment]
@phillipgardiner good idea - please could you create new ticket on Open SDG, link it to here and then close this one. Thank you!

**Comment by phillipgardiner** [comment]
@AnnCorp Ticket added to OpenSDG to use styling for all countries: https://github.com/open-sdg/open-sdg/issues/1055. This ticket will now be closed.

**Comment by phillipgardiner** [comment]
See above
