### ISSUE TITLE
Remove 'Guidance' link from top navigation

### ISSUE THREAD

**Issue by phillipgardiner** [ONSdigital/sdg-indicators#3394]
Currently a 'guidance' option is available in the top level navigation. After making some changes to the sites content, this page is no longer required as all content on that page is also on the 'About' page. The guidance link can therefore be removed.

Note: even before the content was changed the guidance page was pretty much a repeat of a sub section within the about page

**Comment by AnnCorp** [comment]
Actioned by @LucyGwilliamAdmin  - Guidance link on top menu removed when Lucy implemented Open SDG v1.0.0 and the content changes actioned by @phillipgardiner
