### ISSUE TITLE
Indent bullet points on content pages

### ISSUE THREAD

**Issue by phillipgardiner** [ONSdigital/sdg-indicators#3395]
Bullet points within the content pages need to be indented to improve the page readability. This was not able to be achieve within markdown and will therefore have to be undertaken using css.

**Comment by phillipgardiner** [comment]
In additional the line spacing of bullet points needs to be increase, currently they are too close together.

**Comment by AnnCorp** [comment]
@phillipgardiner please could you add the GDS links re this. Thanks

**Comment by phillipgardiner** [comment]
@AnnCorp I stand corrected. If following GDS styling, bullet points are not indented (see copy from GDS guide below)

_Bullet points and steps
You can use bullet points to make text easier to read. Make sure that:

- you always use a lead-in line
- the bullets make sense running on from the lead-in line
- you use lower case at the start of the bullet
- you do not use more than one sentence per bullet point - use commas or dashes to expand on an item
- you do not put ‘or’ or ‘and’ after the bullets
- you do not make the whole bullet a link if it’s a long phrase
- you do not put a semicolon at the end of a bullet
- there is no full stop after the last bullet point__

It seems generally speaking whether to indent or not is a companys individual choice based on their own style guide. Therefore if we are choosing to follow GDS guidence we can close this ticket?

**Comment by AnnCorp** [comment]
@phillipgardiner  thanks for update. I think stick with GDS guidance so I'll close the ticket.
