### ISSUE TITLE
Design changes to 'Updates' page

### ISSUE THREAD

**Issue by phillipgardiner** [ONSdigital/sdg-indicators#3397]
Following the expert review content changes #3392 it was noted a number of design changes are required to the 'updates' page in order to align it with GDS standards. It was decided in weekly tech call these changes would be made to the UK site first and them implement across to Open SDG should they be successful.

A screenshot showing the new design (using word doc) can be seen here: 
![Screenshot (19)](https://user-images.githubusercontent.com/60919820/81670316-551c7400-943f-11ea-9387-aeb968caf37b.png)

The changes compared to the current UK layout are:
- Title of page changed to: Updates on Sustainable Development Goals
- Update title and initial paragraph text to be 16px
- Date format to be: dd, full month name, yyyy
- Category labels to be alongside date (with relevant spacing in between) 
- Date and category font size set to: small  
- Removal of the Post by category option (this is not required at this time due to the small number of current updates shown

@SavvasStephanides any questions about the design just shout -thanks

**Comment by LucyGwilliamAdmin** [comment]
@phillipgardiner title has just been changed as part of accessibility fix

**Comment by AnnCorp** [comment]
@LucyGwilliamAdmin what would be the implications to implement on the UK site as a customisation please or do you think should be in Open SDG. @phillipgardiner anything to add re what's left to do?

**Comment by phillipgardiner** [comment]
@AnnCorp no nothing extra to add, apart from this new design follows GDS guidelines for this type of page. It is just a case of weather this change is for UK only or Open SDG @LucyGwilliamAdmin to advise as don't know the technical but behind this as I remember it could not be changed within mark up

**Comment by phillipgardiner** [comment]
Ticket closed and replaced with ticket in OpenSDG https://github.com/open-sdg/open-sdg/issues/1057
