### ISSUE TITLE
Add union jack flag to main logo image

### ISSUE THREAD

**Issue by phillipgardiner** [ONSdigital/sdg-indicators#3398]
Add union jack image to the main logo image to provide confidence this is the SDG website for the UK. We agrees this would be done using photoshop.

**Comment by phillipgardiner** [comment]
https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf

**Comment by phillipgardiner** [comment]
@AnnCorp @SavvasStephanides 

As stated previously the guidelines published suggest the logo without the 17 steps bit should be used. However there was a team positiveness towards keeping this on the UK site. I have therefore mock up both options in both colour and black and white. Perhaps we could look at which looks best on the site? 

Please note the B&W logo may not show correctly here due to the background being translucent and it sitting on a white page.

![UK-SDG-Logo](https://user-images.githubusercontent.com/60919820/81692815-de8b7080-9456-11ea-89f9-c24e71409fa0.png)

![UK-17-SDG-Logo_BW](https://user-images.githubusercontent.com/60919820/81692808-dc291680-9456-11ea-90a8-546eb60c7435.png)

![UK-17-SDG-Logo](https://user-images.githubusercontent.com/60919820/81692822-e0553400-9456-11ea-80e8-b149be375f94.png)

![UK-SDG-Logo_BW](https://user-images.githubusercontent.com/60919820/81692817-df240700-9456-11ea-9045-49c32c40d995.png)

**Comment by AnnCorp** [comment]
I do like the '17 goals...' version and it looks good freestanding but actually next to the flag, the other logo looks better. I'm happy to go with the first logo version shown above, if that's what guidelines suggest.  We'll have a '17 goals...' heading on our home page anyway so as a package it will all work well together.

**Comment by phillipgardiner** [comment]
@ann have added a verticle line between the flag and the SDG logo as per the SDG guidelines: https://www.un.org/sustainabledevelopment/wp-content/uploads/2019/01/SDG_Guidelines_AUG_2019_Final.pdf

**Comment by SavvasStephanides** [comment]
Thank you @phillipgardiner for the research and the logo mockups. Great job!

Personally I like the first one to be honest, for a couple of reasons: (1) Much cleaner (2) The "17 goals" tagline is written a few pixels underneath in the introduction banner anyway.

**Comment by AnnCorp** [comment]
@SavvasStephanides will add a link to this one in trello for you to look at please.

**Comment by SavvasStephanides** [comment]
Thanks @AnnCorp. Having a look. 

@phillipgardiner is it possible to have a version with transparent background? Mostly the high contrast one, which has a white square around the flag. Thanks!

**Comment by phillipgardiner** [comment]
@SavvasStephanides there should be a 0.5pt line between the flag and the logo (see mine above)

**Comment by SavvasStephanides** [comment]
Thanks @phillipgardiner. You're right. Here's the updated version. I left a bit more spacing between the lines and the graphics. Do you think it's too much?

![image](https://user-images.githubusercontent.com/478770/85415208-f29db400-b564-11ea-86dd-6122c5ee03ea.png)

**Comment by phillipgardiner** [comment]
@SavvasStephanides I don't think its too much, the left hand side is perfect. But according to the guidelines it must be the same size gap on both sides (e.g. to me the space on the right of the line looks bigger than the space on the left? It may need lining up with the start of the letters rather than the edge of that image?

**Comment by SavvasStephanides** [comment]
Keen eye @phillipgardiner. I thought both images were the same distance from the line but I checked and it isn't. Fixed.

![image](https://user-images.githubusercontent.com/478770/85418908-5033ff80-b569-11ea-81a8-49f0b620d38d.png)

**Comment by phillipgardiner** [comment]
@looks good
