### ISSUE TITLE
Customise Prose

### ISSUE THREAD

**Issue by dougmet** [ONSdigital/sdg-indicators#38]
Estimate: 15 days

As it stands prose.io serves most of our needs for managing data. However, we'd like to customise it. Prose is actually a fairly lightweight application and we could fork Prose and run our own version.  We'd need to run a gateway instance, which we can do on heroku for free. Our prose app itself would be hosted on GitHub pages. This ticket can serve as a feature list for what we would do when we customise prose.

- Allow nested metadata entries #35 
- Check for outstanding PRs on a dataset #26 
- A nice ONS styling
- Customise messages #26 
- No granting access to external application #55 
- Data validation on input page #61 
- Preview the metadata before committing

**Comment by brockfanning** [comment]
@dougmet I was discussing this with @philipashlock as something the US platform could benefit from as well. The improvements listed above sound like a huge upgrade to the data provider UX. Have you already forked Prose and started customising? If so I'd be happy to contribute where possible.

**Comment by dougmet** [comment]
Hi @brockfanning, that's great! Afraid I didn't get far with this. As a test I did fork prose and run my own service from Heroku, as per their instructions, and it worked. However, I didn't change the code. Apart from custom styling (which is not an immediate concern) I can imagine that we would want most of the same features.

**Comment by dougmet** [comment]
Leaving this open just a tiny bit longer so that the inbound devs can see that we were thinking about it. If they have sufficient node skills they may consider it.
